apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "static-wellknown.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "static-wellknown.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "static-wellknown.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "static-wellknown.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          readinessProbe:
            httpGet:
              path: /.well-known/matrix/server
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /.well-known/matrix/server
              port: http
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "static-wellknown.fullname" . }}
