{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mas.postgresql.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mas.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mas.postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mas.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: postgresql
      {{- include "mas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgresql
        {{- include "mas.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          ports:
            - name: postgresql
              containerPort: 5432
          env:
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgresql.database }}
            - name: POSTGRESQL_USERNAME
              value: {{ .Values.postgresql.username }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mas.fullname" . }}
                  key: mas-db-password
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgresql.username }}
                - -d
                - {{ .Values.postgresql.database }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgresql.username }}
                - -d
                - {{ .Values.postgresql.database }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources.postgresql | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mas.postgresql.fullname" . }}-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mas.postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mas.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      name: postgresql
  selector:
    app.kubernetes.io/component: postgresql
    {{- include "mas.selectorLabels" . | nindent 4 }}
{{- end }}
